### ISSUE TITLE
Bug? ao entrar no canal. (tem chance de ser erro meu tbm.)

### ISSUE THREAD

**Issue by MrChuw** [Bobotinho/bot#8]
Se eu deixar aqui como estar 
![image](https://user-images.githubusercontent.com/14945734/132684300-b53ea3f1-6769-40c9-8716-830dfab73d41.png)

Ele vai dar esse erro 
![image](https://user-images.githubusercontent.com/14945734/132684340-5e95adc9-4c27-4efc-afa3-6cbf77226efb.png)

Mais se eu mudar 
![image](https://user-images.githubusercontent.com/14945734/132684388-380c2f30-4ce9-44f0-8660-f10c467b6cde.png)

Ele roda normalmente 
![image](https://user-images.githubusercontent.com/14945734/132684838-623308c7-c276-47ae-b66e-dd0678bdd089.png)

**Comment by leandcesar** [comment]
`self.owner` é obtido da variável de ambiente `OWNER_NAME`, essa atribuição é feita no arquivo [**config.py**](https://github.com/Bobotinho/bot/blob/main/bobotinho/config.py).

Existem várias maneiras de definir suas variáveis de ambiente. Caso não tenha familiaridade, elas são feitas por um arquivo `.env` ou `.envrc` na raíz do diretório. Isso dependerá também se você está usando ou não um ambiente virtual (via [**venv**](https://docs.python.org/3/library/venv.html), [**virtualenv**](https://virtualenv.pypa.io/en/latest/), [**pyenv**](https://github.com/pyenv/pyenv), ou outro) e do editor que você utiliza (o [**VS Code**](https://code.visualstudio.com/), por exemplo, carrega automaticamente as variáveis do arquivo `.env`). 

Escolha uma forma de configurar suas variáveis de ambiente e, então, adicione a variável `OWNER_NAME` com o seu nome de usuário da Twitch (assim como o `ACCESS_TOKEN`). Por exemplo, um arquivo `.env`:

```
ACCESS_TOKEN=seu-token-de-acesso
OWNER_NAME=mrchuwtructoid
```

Ou, caso prefira utilizar o [**direnv**](https://direnv.net/), crie um arquivo `.envrc`:

```
export ACCESS_TOKEN=seu-token-de-acesso
export OWNER_NAME=mrchuwtructoid
```

Isso deverá resolver.

Se tiver problemas, estou a disposição.

**Comment by MrChuw** [comment]
ppL funcionou, foi mau, é que eu não tenho o costume de usar env, eu so tenho mais uma duvida como eu faco para adicionar ele a outros canais?

**Comment by leandcesar** [comment]
Existem duas maneiras:

- A mais simples: no arquivo [**bots/twitch.py**](https://github.com/Bobotinho/bot/blob/main/bobotinho/bots/twitch.py), onde é feita a construção da classe `TwitchBot`, passe uma lista com os nomes dos canais no argumento `initial_channels`. Segue o trecho:

```py
class TwitchBot(Bot):
    def __init__(self, config):
        super().__init__(
            token=config.access_token,
            client_secret=config.client_secret,
            prefix=config.prefix,
            case_insensitive=True,
            initial_channels=["channel_1", "channel_2"],  # add channels here
        )
```

Essa não é a forma esperada, e diversos comandos (como `%start` e `%stop`) não irão funcionar. Mas dependendo do seu objetivo, pode ser suficiente.

- A mais robusta: quando você roda o bot localmente, se você não tiver especificado nenhum banco de dados (via variável de ambiente `DATABASE_URL`), será criado automaticamente um arquivo `db.sqlite3`. Esse é seu banco de dados local. Para adicionar um canal, você deve inserí-lo no banco, usando:

```SQL
INSERT INTO public.user (id, name) VALUES (123, 'channel_1');
INSERT INTO public.user (user_id) VALUES (123);
```

Onde `id` e `user_id` são o ID do usuário da Twitch e `name` é o nome de usuário da Twitch. Se optar por essa forma, lembre-se de adicionar também o seu próprio canal.

**Comment by MrChuw** [comment]
Voltei e eu acho que achei o problema. 
![image](https://user-images.githubusercontent.com/14945734/132746516-6796996e-b8bd-4be7-bbbe-f91602552e31.png)
![image](https://user-images.githubusercontent.com/14945734/132746596-1473e7fd-5d38-41c1-886b-da0c21ae01e6.png)
![image](https://user-images.githubusercontent.com/14945734/132746819-6c112a8b-0638-42ff-8df4-d25dea2ddb7a.png)
![image](https://user-images.githubusercontent.com/14945734/132747099-90f7883b-3a79-46ab-9029-77470ae5a9d5.png) um script que eu achei para pegar todas as variáveis 
![image](https://user-images.githubusercontent.com/14945734/132747185-612e9588-5fcf-4f20-a9b6-8a28329950ba.png)

ele não esta pegando as variáveis do sistema, eu fiz como você disse e coloquei "export OWNER_NAME=mrchuwtructoid", eu estou usando um raspberry pi 3b+ com o raspbian

**Comment by leandcesar** [comment]
`export OWNER_NAME=mrchuwtructoid` precisa estar em um arquivo `.envrc`, e isso exige que você esteja em um ambiente virtual e com o [**direnv**](https://direnv.net/) instalado. Você precisa saber como utilizar variáveis de ambiente, tem um [**exemplo aqui**](https://blog.adam-uhlir.me/python-virtual-environments-made-super-easy-with-direnv-307611c3a49a).

E para executar os comandos do banco, você precisa estar conectado ao banco. Você precisa saber como se conectar ao banco sqlite, tem um [**exemplo aqui**](https://iotbytes.wordpress.com/sqlite-db-on-raspberry-pi/).
